import unittest


class TestExceptions(unittest.TestCase):

    def test_raise_pypfop_error(self):
        pass

    def test_raise_document_generator_error(self):
        pass

    def test_builder_error(self):
        pass

    def test_template_error(self):
        pass
